# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joel Schoolnik
email: tivrama@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging to keep myself organized through the journey to becoming a Software Engineer.  Please feel free to email me if you have suggestions, or cautions of any pitfalls.   

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tivrama.github.io/" # the base hostname & protocol for your site
# twitter_username: silence
github_username:  tivrama

# Build settings
markdown: kramdown
